sparkfun/SparkFun_RTK_Everywhere_Firmware

- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/menuPP.ino
Changes:
* Only display first two bytes of token
* Display JSON message, don't use serializeJsonPretty
* No longer display hex dumps
* Display byte count for JSON message
* Display byte count for response
* Display MQTT received byte count
> Update pointPerfect debugging

- Firmware/RTK_Everywhere/AP-Config/index.html
- Firmware/RTK_Everywhere/AP-Config/src/main.js
- Firmware/RTK_Everywhere/Form.ino
- Firmware/RTK_Everywhere/NVM.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/menuCommands.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/settings.h
HAS/E6 enable/disable under GNSS
Add Ports menu for Torch.
Add USB GNSS output enable/disable under Ports
Remove Debug Zone / Reset counter
Update Torch default ARP and tooltip.
Add Tilt menu.
Enable/disable tilt
Pole length
Add auto-firmware update to system menu
Add Measurement scale to system menu
Add Beeper control to system menu
Add rebootMinutes feature to system menu
> Add new features to Web Config page

- Firmware/RTK_Everywhere/AP-Config/src/main.js
- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/System.ino
- Firmware/RTK_Everywhere/menuBase.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/settings.h
This PR contains the same changes I made recently to the RTK Firmware:
* L-Band frequency is chosen based on location - or geographicRegion if fix is not available
* Corrects the coordinates type detection in main.js
* Adds NTRIP Server Caster User and PW to menuBase
* Better periodic and debug printing - especially for NTRIP Server
* Don't disable settings.enableNtripServer when all server connections are closed
* Adds the same server and client stops vs. restarts fixes as RTK Firmware
* Resolves issue #335 
* I still don't understand why the crash is happening, but commit 9d56cd47aaa1a03877869733323b318affce1a54 fixes it...
* Don't disable settings.enablePointPerfectCorrections when the MQTT connection closes
> Changes from RTK Firmware

- Firmware/RTK_Everywhere/makefile
Match partition size specified in RTKEverywhere.csv
> Fix upload partition size, reduce flash usage from 97% to 48%

- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/Tools/TCP_Client.py
- Firmware/Tools/TCP_Server.py
This PR:
Removes one WiFi dependency from TCPServer.ino. @LeeLeahy2 please review this change: f6d84412f25e60704420e9560108f56ee252f5e7
Adds TCP_Client.py and TCP_Server.py - used to check TCP on EVK (via Ethernet)
> TCP updates

- Firmware/RTK_Everywhere/AP-Config/src/main.js
Allow EVK to have zero WiFi networks defined (for firmware update via Ethernet)
Change "WiFi" to "Network"
> EVK web config changes

- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
This fixes a bug in ```networkGetActiveType```
@LeeLeahy2 : please review my changes in 3fd8fa5c2caef0817fe5cab77fb5dce34cfea42e. I can think of two solutions. I'm not sure what your intent was here. Thanks!
> Fix error in networkGetActiveType - resolves #370

- Firmware/RTK_Everywhere/Base.ino
- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/ESPNOW.ino
- Firmware/RTK_Everywhere/LoRa.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/Tasks.ino
- Firmware/RTK_Everywhere/menuMain.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/settings.h
- Firmware/RTK_Everywhere/support.ino
Add support for internal LoRa radio in the Torch based on the STM32.
> Add LoRa Radio control

- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/menuPP.ino
It looks like there was some badness on/around July 9th where there was updates to menuPP, a series of merges and reverts, causing problems and corrupting main. This PR should resolve all those issues on main.
> Fix merge conflicts

- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/Cellular.ino
- Firmware/RTK_Everywhere/LARA.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/settings.h
> Cellular: Add LARA and Cellular support

- Firmware/RTK_Everywhere/settings.h
The network sequences should never change!
> Network: Move NETWORK_POLL_SEQUENCEs from RAM into flash

- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/ESPNOW.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
Commenting out COMPILE_NETWORK alone still fails
> Verify COMPILE_* for AP, CELLULAR, ESPNOW, ETHERNET, MQTT, OTA and WIFI

- Firmware/RTK_Everywhere/WiFi.ino
WiFi: Move constants and variables
WiFi: Move wifiNetworkCount
WiFi: Move wifiPrintState
WiFi: Move wifiDisplayState
WiFi: Move menuWiFi
WiFi: Move wifiResetTimeout
WiFi: Move wifiStart
WiFi: Move wifiStop
WiFi: Move wifiEvent
WiFi: Rename wifiRestartRequested to restartWiFi
> WiFi: Move code and merge restartWiFi variables

- Firmware/RTK_Everywhere/GNSS_Mosaic.ino
Remove redundant gnss-> pointers
Remove redundant comments
Correct getLoggingType() - bad use of loggingType
Perform a soft reset when SD card is inserted or removed (probably needs a "displayCardChange" on the OLED)
> Mosaic logging improvements

- Firmware/RTK_Everywhere/ESPNOW.ino
- Firmware/RTK_Everywhere/Network.ino
Network: Move code
Network: Fix comments and remove blank lines
ESP-NOW: Rename peerBroadcast to espnowBroadcastAddr
ESP-NOW: Add module comment
ESP-NOW: Rename espNowDebug to settings.debugEspNow
ESP-NOW: Remove espNowVerbose
ESP-NOW: Replace espNowDisplay with settings.debugEspNow
> Minor changes: Move code, update comments, rename routines, use settings

- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/WiFi.ino
WiFi: Set enable false in RTK_WIFI::stopStart
WiFi: Don't stop WiFi for most WiFi events
WiFi: Notify network of IP loss when WiFi station stops
Network: Only call WIFI_STOP once
> Bug fixes: Fix major issues found during debugging

- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/WiFi.ino
Network: Add networkGetCurrentInterfaceIndex routine
WiFi: Use start script to restart WiFi
WiFi: Change wifiStationReconnectionRequest to return bool
> WiFi: Rework restart mechanism

- Firmware/RTK_Everywhere/TcpClient.ino
TCP Client: Create a single point to start and stop the network
TCP Client: Add consumer support to start and stop the network
TCP Client: Always start without any connection delay
> Tcp client: Use new network consumer mechanism

- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/settings.h
HTTP_Client: Separate routines
HTTP_Client: Create one place for HTTP start/stop
HTTP_Client: Add NETCONSUMER_HTTP_CLIENT
HTTP_Client: Use networkConsumer routines to start and stop the network
> HTTP_Client: Add new WiFi and network consumer support

- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/WebServer.ino
Network: Add soft AP consumer support
> WebServer: Switch from wifiSoftApOn to networkSoftApConsumer*

- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/UdpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuPP.ino
Network Clients: Remove *NeedsNetwork routines
NtripServer: Separate routines
NtripServer: Create one place for NtripServer start/stop
NtripServer: Cleanup ntripServerStop shutdown path
> NtripServer: Cleanup start and stop path

- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
NtripClient: Disable connection limit
MQTT_Client: Disable connection limit
HTTP_Client: Disable connection limit
NtripServer: Disable connection limit
> Network: Remove the connection limits

- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/Ethernet.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/PointPerfectLibrary.ino
- Firmware/RTK_Everywhere/System.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuCommands.ino
- Firmware/RTK_Everywhere/menuMain.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/support.ino
NtripClient: Add routine separation
NtripClient: Move ntripClientForceShutdown
NtripClient: Add and use ntripClientEnabled routine
NtripClient: Use common code to handle network failures
NtripClient: Move ntripClientPriority setting into ntripClientStop
> NTRIP Client

- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/Ethernet.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NVM.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/PointPerfectLibrary.ino
- Firmware/RTK_Everywhere/System.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuCommands.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuMain.ino
- Firmware/RTK_Everywhere/menuMessages.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/support.ino
menuFirmware: Set otaPriority in otaUpdateStop
menuFirmware: Set otaPriority in otaUpdateStop
menuFirmware: Rename getFirmwareVersion to firmwareVersionGet
Rename isReportedVersionNewer to firmwareVersionIsReportedNewer
menuFirmware: Rename scanForFirmware to microSdScanForFirmware
menuFirmware: Rename mountSDThenUpdate to microSdMountThenUpdate
menuFirmware: Rename menuFirmware to firmwareMenu
menuFirmware: Rename, alphabetize, group routines, eliminate #ifdefs
menuFirmware: Add otaMenuDisplay and otaMenuProcessInput routines
menuFirmware: Verify file exists on SD card before shutting down tasks
> OTA Update

- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/Ethernet.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NVM.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/PointPerfectLibrary.ino
- Firmware/RTK_Everywhere/System.ino
- Firmware/RTK_Everywhere/Tasks.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuCommands.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuMain.ino
- Firmware/RTK_Everywhere/menuMessages.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/support.ino
TcpClient: Separate routines
TcpClient: Rename discardTcpClientBytes to tcpClientDiscardBytes
> TCP Client

- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/Ethernet.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NVM.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/PointPerfectLibrary.ino
- Firmware/RTK_Everywhere/System.ino
- Firmware/RTK_Everywhere/Tasks.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/UdpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuCommands.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuMain.ino
- Firmware/RTK_Everywhere/menuMessages.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/support.ino
UdpServer: Separate routines
UdpServer: Alphabetize routines
UdpServer: Rename discardUdpServerBytes to udpServerDiscardBytes
UdpServer: Move udpServerPriority into udpServerStop
UdpServer: Add and use udpServerEnabled
UdpServer: Start and stop the network
UdpServer: Update testing documentation
> UDP Server

- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/Ethernet.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NVM.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/PointPerfectLibrary.ino
- Firmware/RTK_Everywhere/System.ino
- Firmware/RTK_Everywhere/Tasks.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuCommands.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuMain.ino
- Firmware/RTK_Everywhere/menuMessages.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/support.ino
TcpServer: Separate routines
TcpServer: Move discardTcpServerBytes routine
TcpServer: Add tcpServerEnabled routine
TcpServer: Start and stop the network
TcpServer: Rename discardTcpServerBytes to tcpServerDiscardBytes
TcpServer: Add testing documentation
> TCP Server

- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NTP.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/UdpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/settings.h
HTTP_Client: Perform the enable check once
HTTP_Client: Move network failure check to top of httpClientUpdate
> HTTP_Client: Use common client organization

- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NTP.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/UdpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/settings.h
TcpServer: Rename connected to clientConnected
Network: Add networkGetPriority
Network: Connect immediately following network interface change
> Network: Connect immediately following network interface change

- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NTP.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/UdpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuPP.ino
- Firmware/RTK_Everywhere/settings.h
MQTT_Client: Perform the enable check once
MQTT_Client: Move network failure check to top of mqttClientUpdate
> MQTT_Client: Use common client organization

- Firmware/RTK_Everywhere/NTP.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/TcpClient.ino
TcpClient: Perform the enable check once
TcpClient: Move network failure check to top of tcpClientUpdate
> TcpClient: Use common client origanization

- Firmware/RTK_Everywhere/Begin.ino
> Increase tolerances

- Firmware/RTK_Everywhere/Begin.ino
- Firmware/RTK_Everywhere/Developer.ino
- Firmware/RTK_Everywhere/ESPNOW.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuCommands.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuMain.ino
ESP-NOW: Add wifiEspNowOff
WiFi: Add wifiSoftApOff
WiFi: Add wifiStationOff
> Network: Add wifiEspNowOff, wifiSoftApOff and wifiStationOff

- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/NTP.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/NtripServer.ino
- Firmware/RTK_Everywhere/TcpClient.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/UdpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/menuFirmware.ino
- Firmware/RTK_Everywhere/menuPP.ino
HTTP_Client: Call networkUserAdd
MQTT_Client: Call networkUserAdd
NTP: Call networkUserAdd
NtripClient: Call networkUserAdd
NtripServer: Call networkUserAdd
TcpClient: Call networkUserAdd and networkConsumerOffline
TcpServer: Call networkUserAdd and networkConsumerOffline
UdpServer: Call networkUserAdd
WebServer: Call networkUserAdd and networkUserRemove
> Network Clients: Add user support

- Firmware/RTK_Everywhere/LARA.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/settings.h
Network: Fix parameter being passed into networkDelay
Network: Add index to networkInterfaceTable, verify index/def priority
LARA: Add the laraTimerStart routine
LARA: Verify highest priority before starting
> Don't start cellular if WiFi starts

- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/settings.h
WebServer: Add GET_PAGE macro
WebServer: Remove a level of indirection from wsserver
WebServer: Display the HTTPD configuration
WebServer: Move variables from RTK_Everywhere.ino into WebServer.ino
Reduce the size of the web socket server stack (23K --> 8K)
Reduce the web server's task stack size (23K --> 4K)
Remove network user when the connection is lost
Add bit to periodically display the web server state
WebServer: Support debugging of web socket server
* Don't display entire packet, display and dumping of 3K packet exceeds time to enable parsing!
> WebServer: Fix to work with new WiFi layer

- Firmware/RTK_Everywhere/Cellular.ino
- Firmware/RTK_Everywhere/Display.ino
- Firmware/RTK_Everywhere/Ethernet.ino
- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/RTK_Everywhere.ino
- Firmware/RTK_Everywhere/States.ino
- Firmware/RTK_Everywhere/TcpServer.ino
- Firmware/RTK_Everywhere/WebServer.ino
- Firmware/RTK_Everywhere/WiFi.ino
- Firmware/RTK_Everywhere/menuSystem.ino
- Firmware/RTK_Everywhere/settings.h
Network: Add fileName and lineNumber to networkSequenceExit
Network: Add fileName and lineNumber to networkSequenceStopPolling
Network: Add fileName and lineNumber to networkSequenceStop
Network: Add fileName and lineNumber to networkSequenceStart
Network: Add fileName and lineNumber to *InterfaceInternetConnectionLost
Network: Add fileName & lineNumber to networkInterfaceEventInternetLost
> Network: Add fileName and lineNumber to various calls

- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/makefile
- Firmware/RTK_Everywhere/menuMain.ino
Rebase on #652 
Changes:
* menuMain: Remove setting of periodicDisplay, set by RTK_Everywhere
Fix bug of duplicate WiFi IP address display
* Network: Fix bug in networkIsHighestPriority
* Network: Fix display of network consumers
> Network: Fix minor bugs

- Firmware/RTK_Everywhere/HTTP_Client.ino
- Firmware/RTK_Everywhere/MQTT_Client.ino
- Firmware/RTK_Everywhere/Network.ino
- Firmware/RTK_Everywhere/NtripClient.ino
- Firmware/RTK_Everywhere/TcpClient.ino
This change includes:
* Network: Add networkUseDefaultInterface routine
* Network: Add *InterfacePriority, *InterfaceRunning and loss diagram
> Network: Add new routines
