Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/States.ino
Firmware/RTK_Everywhere/WiFi.ino

If WiFi is active, then WiFi Config is started, the network layer will shut down the AP, and start WiFi again. This PR prevents the network layer from running while in WiFi config mode.

Allow entry into browser config if WiFi is on

---

Firmware/RTK_Everywhere/Begin.ino
Firmware/RTK_Everywhere/MQTT_Client.ino
Firmware/RTK_Everywhere/PointPerfectLibrary.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/States.ino
Firmware/RTK_Everywhere/Tasks.ino
Firmware/RTK_Everywhere/menuPP.ino
Firmware/RTK_Everywhere/menuSystem.ino
Firmware/RTK_Everywhere/settings.h

If we stay in RTK Float (or 3D fix) for more than 180 seconds, re-initialize the PPL.

Reset PPL if RTK Float Lock is detected

---

Firmware/RTK_Everywhere/NtripServer.ino

I'm seeing the code crash at line 400 when I add a second NTRIP Server (when the first is already running).
I think we're calling connected when the networkClient hasn't yet been initialized?

Prevent crash calling uninitialized NTRIP Server networkClient

---

Firmware/RTK_Everywhere/UdpServer.ino
Firmware/RTK_Everywhere/menuSystem.ino
Firmware/Tools/UDP_Client.py

This PR corrects UDP Server when running on Ethernet on EVK. In particular, it removes a WiFi dependency.
Tested with UDP_Client.py.
@LeeLeahy2 : please review my changes, especially ba4071aef2e5622987ff5a99d6950c34d06a06e7

Fix UDP Server on Ethernet (EVK)

---

Firmware/RTK_Everywhere/WiFi.ino

If AP_STA mode is needed, we need to continue even if wifiIsConnected...
A nasty flaw... It's been there for quite a while... Embarrassing really.

Only exit wifiConnect early when connected && AP_STA mode is not needed

---

Firmware/RTK_Everywhere/Bluetooth.ino
Firmware/RTK_Everywhere/bluetoothSelect.h
Firmware/RTK_Everywhere/src/BluetoothSerial/BTAddress.cpp
Firmware/RTK_Everywhere/src/BluetoothSerial/BTAddress.h
Firmware/RTK_Everywhere/src/BluetoothSerial/BTAdvertisedDevice.h
Firmware/RTK_Everywhere/src/BluetoothSerial/BTAdvertisedDeviceSet.cpp
Firmware/RTK_Everywhere/src/BluetoothSerial/BTScan.h
Firmware/RTK_Everywhere/src/BluetoothSerial/BTScanResultsSet.cpp
Firmware/RTK_Everywhere/src/BluetoothSerial/BluetoothSerial.cpp
Firmware/RTK_Everywhere/src/BluetoothSerial/BluetoothSerial.h

Bring back bluetooth serial library

---

Firmware/RTK_Everywhere/TcpServer.ino
Firmware/RTK_Everywhere/UdpServer.ino
Firmware/RTK_Everywhere/menuSystem.ino
Firmware/RTK_Everywhere/support.ino

Lee's PR #425 worries me a bit. For me. the IPAddress prints OK without the c_str. But, just in case, this PR changes the remaining systemPrint toString's to c_str.

Change remaining systemPrint IPAddress toString to c_str

---

Firmware/RTK_Everywhere/Begin.ino
Firmware/Test Sketches/System_Check/Begin.ino
Firmware/Test Sketches/System_Check/settings.h

This PR:
* Changes the way the ```idWithAdc``` identifies the board based on ADC voltage and ID resistor values and tolerance 
* The ADC Vref fuse settings on some modules were causing the reported voltage to be out of range
* EVK needs a larger tolerance to compensate
* Improves debug reporting should the ID check fail

Better idWithAdc

---

Firmware/RTK_Everywhere/menuPP.ino

This PR will resolve issue #431. It restructures ```updateProvisioning``` a little and ensures ```requestKeyUpdate``` is always cleared (even if provisioning fails). The user can set ```requestKeyUpdate``` via the PP menu, or the Mode button, or the web config.

Fix flaw in updateProvisioning. Ensure requestKeyUpdate is cleared

---

Firmware/RTK_Everywhere/RTK_Everywhere.ino

Maintain the version number in only one location:
.github/workflows/compile-rtk-everywhere.yml
Look for:
CORE_VERSION
and
run: arduino-cli lib install

Remove library version numbers

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/ESPNOW.ino
Firmware/RTK_Everywhere/ESPNOW_old.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/WiFi_old.ino
Firmware/RTK_Everywhere/settings.h

WiFi: Rename WiFi.ino to WiFi_old.ino
WiFi: Add new WiFi code, remove calls to espNowStart and espNowStop
ESP-NOW: Rename ESPNOW.ino to ESPNOW_old.ino
ESP-NOW: Add new ESP-NOW code
WiFi: Use network layer mDNS routines
WiFi: Switch from _debug to settings.debugWifiState
WiFi: Remove use of _display
WiFi: Pass verbose setting in during constructor
WiFi: Remove start and stop of wifiEventHandler
WiFi: Display start and stop components
WiFi: Add start WiFi station components comment
WiFi: Start and stop the DNS server
WiFi: Don't display restarted items as failed to stop

Add new WiFi and ESP-NOW layer code, add _old to previous file names

---

Firmware/RTK_Everywhere/HTTP_Client.ino
Firmware/RTK_Everywhere/MQTT_Client.ino
Firmware/RTK_Everywhere/NTP.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/NtripClient.ino
Firmware/RTK_Everywhere/NtripServer.ino
Firmware/RTK_Everywhere/TcpClient.ino
Firmware/RTK_Everywhere/TcpServer.ino
Firmware/RTK_Everywhere/UdpServer.ino
Firmware/RTK_Everywhere/WebServer.ino
Firmware/RTK_Everywhere/menuFirmware.ino
Firmware/RTK_Everywhere/menuPP.ino

Ensure that each client and server gets notified of the network failover
in a timely manor.  Using networkHasInternet may either not change or
only a subset of clients and servers may get notified.  Using
networkIsConnected ensures that the client gets rapid notification of
the failover.

Fix network failover detection

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/settings.h

WiFi: Initialize wifiRestartRequested in RTK_WIFI constructor
WiFi: Make RTK_WIFI::_timer a global: wifiReconnectionTimer
WiFi: Add clearStarted routine
WiFi: Make stopStart public
WiFi: Initiate the WiFi reconnection
* Move RTK_WIFI::stationReconnection to wifiStationReconnectionRequest
* Call wifiStationReconnectionRequest when the reconnection timer is
running (non-zero)
WiFi: Stop connection timer when WiFi stops or connection successful
Network: Validate the index
Network: Use networkInterfaceHasInternet where possible
Network: Let networkInterfaceInternet* and networkStop clear flags
Network: Add more debug output
Network: Move routines *ConnectionLost & *ConnectionAvailable

Add WiFi restart support

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Display.ino
Firmware/RTK_Everywhere/ESPNOW.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/TcpServer.ino
Firmware/RTK_Everywhere/UdpServer.ino
Firmware/RTK_Everywhere/WebServer.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/menuMain.ino
Firmware/RTK_Everywhere/settings.h

RTK: Add headers for WiFi and MQTT support
WiFi: Make RTK_WIFI::_stationRunning a global: wifiStationRunning
WiFi: Make RTK_WIFI::_softApRunning a global: wifiSoftApRunning
WiFi: Make RTK_WIFI::_espNowRunning a global: wifiEspNowRunning
WiFi: Remove WIFI_IS_RUNNING macro and RTK_WIFI::running
WiFi: Make RTK::_channel a global: wifiChannel
ESP-NOW: Use espNowIsPaired instead of ESPNOW_IS_PAIRED macro

Reduce the use of macros, use global variables or call routines directly

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Display.ino
Firmware/RTK_Everywhere/ESPNOW.ino
Firmware/RTK_Everywhere/Ethernet.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/NtripClient.ino
Firmware/RTK_Everywhere/NtripServer.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/menuCommands.ino
Firmware/RTK_Everywhere/menuFirmware.ino
Firmware/RTK_Everywhere/settings.h

Network: Add updated network consumer support
Network: Use new networkConsumer routines to start/stop the network
NtripClient: Start using networkConsumer services
NtripClient: Switch back to using *ClientRestart instead of *ClientStop
NtripServer: Switch back to using *ServerRestart instead of *ServerStop
OtaClient: Start/stop network layer
Network: Add networkStartNextInterface routine to initiate failover
Network: Use networkStartNextInterface to initiate failover
WiFi: Stop the start sequence once WiFi station starts
WiFi: Stop WiFi reconnection attempts when no network consumers
WiFi: Perform 2 connection attempts with new SSID/pass before failover
menuFirmware: Use wifiStopAll instead of WIFI_STOP
Network: Rename NETWORK_WIFI to NETWORK_WIFI_STATION
WiFi: Rename wifiStart to …

New network consumer support, first part

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/MQTT_Client.ino
Firmware/RTK_Everywhere/menuPP.ino

MQTT_Client: Separate routines
MQTT_Client: Alphabetize routines
MQTT_Client: Add mqttClientEnabled routine
MQTT_Client: Use the mqttClientEnabled routine for consistent checks
MQTT_Client: Break up the mqttClientReceiveMessage routine
MQTT_Client: Create one place for MQTT start/stop
MQTT_Client: Enable MQTT start and stop
MQTT_Client: Use networkConsumer routines to start and stop the network
MQTT_Client: Restart immediately after connected and network failure
MQTT_Client: Add debug message upon successful subscription

MQTT_Client: Add new WiFi and network consumer support

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Display.ino
Firmware/RTK_Everywhere/Ethernet.ino
Firmware/RTK_Everywhere/GNSS.h
Firmware/RTK_Everywhere/GNSS_LG290P.h
Firmware/RTK_Everywhere/GNSS_LG290P.ino
Firmware/RTK_Everywhere/GNSS_Mosaic.h
Firmware/RTK_Everywhere/GNSS_Mosaic.ino
Firmware/RTK_Everywhere/GNSS_None.h
Firmware/RTK_Everywhere/GNSS_UM980.h
Firmware/RTK_Everywhere/GNSS_UM980.ino
Firmware/RTK_Everywhere/GNSS_ZED.h
Firmware/RTK_Everywhere/GNSS_ZED.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/States.ino
Firmware/RTK_Everywhere/WebServer.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/settings.h

WebServer: Separate routines
WebServer: Alphabetize routines
GNSS: Move createMessageList and createMessageListBase into GNSS
WebServer: Update error messages
WebServer: Move online.webServer
WiFi: Make soft AP SSID and password global
WiFi: Support no password for soft AP
WiFi: Use local variable for hostName
WiFi: Expose wifi*Online variables
WiFi: Add routines to get soft AP IP addr and station SSID and IP addr
Network: Allow multiple calls to networkConsumerRemove
States: Don't force RTK CONFIG as soft AP SSID
WiFi: Add wifiSoftApOn routine to start/stop soft AP
WebServer: Start and stop the network
Display: Move globals into displayConfigViaWiFi
Display: Simplify display of WiFi config values
WiFi: Eliminate magic number for SSID_LENGTH
Network: Add more debug prints
WebServer: Move …

WebServer: Add new WiFi and network consumer support

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Display.ino
Firmware/RTK_Everywhere/HTTP_Client.ino
Firmware/RTK_Everywhere/MQTT_Client.ino
Firmware/RTK_Everywhere/NTP.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/NtripClient.ino
Firmware/RTK_Everywhere/NtripServer.ino
Firmware/RTK_Everywhere/States.ino
Firmware/RTK_Everywhere/TcpClient.ino
Firmware/RTK_Everywhere/TcpServer.ino
Firmware/RTK_Everywhere/UdpServer.ino
Firmware/RTK_Everywhere/WebServer.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/menuFirmware.ino
Firmware/RTK_Everywhere/menuPP.ino
Firmware/RTK_Everywhere/settings.h

NTP: Move network check to top of ntpServerUpdate routine
NTP: Always periodically display the NTP state
NTP: Fix display of remote IP address
NTP: Add the NTP_STATE_WAIT_NETWORK state
NTP: Add the NTP network consumer
NTP: Separate the routines
NTP: Rename configureUbloxModuleNTP to ntpConfigureUbloxModule
NTP: Perform the enabled check once

NTP: Use common client organization

---

Firmware/RTK_Everywhere/menuPP.ino

menuPP: Remove PROVISIONING_WAIT_RTC state
menuPP: Remove PROVISIONING_NOT_STARTED state
menuPP: Remove PROVISIONING_CHECK_ATTEMPT state
menuPP: Remove PROVISIONING_STARTING state
menuPP: Add provisioningKeysNeeded routine
menuPP: Remove PROVISIONING_WAIT_ATTEMPT state
* Add provisioningStop routine to reset state
* Update provisioningEnabled routine to start every 24 hours

menuPP: Simplify the state machine

---

Firmware/RTK_Everywhere/Display.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/System.ino

Move verifyTables to later in the boot sequence to enable HALT display

Display: Add displayHalt routine, call from reportFatalError

---

Firmware/RTK_Everywhere/States.ino
Firmware/RTK_Everywhere/WebServer.ino

Requires #643
* States: Don't start ESP-NOW early, causes WiFi STA channel conflict
* States: Use RTK_Caster and RTK_Config as base soft AP name
* WebServer: Remove DNSServer, should be handled by the network

Move to common point between release_candidate and leeUpdates

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/support.ino

Rebase on #654 
Changes:
* WiFi: Add wifiVerifyTables
* Network: Add networkUserBits and networkUserCount
* WiFi: Add *GetStateName, *SetState and WiFi station restart states
* WiFi: Add wifiStationEnabled and wifiUpdateSettings
The routines setup and menuWiFi call wifiUpdateSettings to determine if
the SSIDs are available for WiFi station and soft AP and trigger a WiFi
station restart.
The wifiStationEnabled determines if the WiFi station state machine
should start.
* WiFi: Add wifiStationUpdate
Use WIFI_CONNECTION_STABLE_MSEC to determine when it is time to reset
the connectionAttempts and startTimeout.

Add some routines to Network and WiFi

---

Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/WiFi.ino
Firmware/RTK_Everywhere/makefile
Firmware/RTK_Everywhere/menuMain.ino
Firmware/RTK_Everywhere/settings.h
Firmware/RTK_Everywhere/support.ino

Rebase on #655 
Changes:
* WiFi: Change "WiFi" to "WiFi Station" in networkInterfaceTable
* Network: Update periodically display to show more data
* WiFi: Switch to using *SsidSet variables set in wifiUpdateSettings
* WiFi: Use new restart based upon wifiStationUpdate

WiFi: Switch to new restart

---

Firmware/RTK_Everywhere/AP-Config/index.html
Firmware/RTK_Everywhere/Developer.ino
Firmware/RTK_Everywhere/Network.ino
Firmware/RTK_Everywhere/RTK_Everywhere.ino
Firmware/RTK_Everywhere/Tasks.ino
Firmware/RTK_Everywhere/TcpServer.ino
Firmware/RTK_Everywhere/menuCommands.ino
Firmware/RTK_Everywhere/settings.h

Remember to enable some RTCM messages, link fails when no RTCM data is being sent!
Changes:
* TcpServer: Periodically display data sent messages for all clients
* TcpServer: Output TCP Server, NTRIP Caster or Base Caster messages
* TcpServer: Make port selection in tcpServerEnabled
* TcpServer: Determine operating mode in tcpServerEnabled
* TcpServer: Select WiFi mode in tcpServerEnabled
* TcpServer: Move the client handling into tcpServerClientUpdate
* TcpServer: Rework the client connection logic
* TcpServer: Periodically display all of the client connections
* TcpServer: Separate the tcpServerTimer from the tcpServerClientTimers
* TcpServer: Use client states to wait for and process caster request
* TcpServer: Handle client allocation failures
* TcpServer: Don't send data until the …

Update TCP server to better work as an NTRIP or base caster

---

Firmware/RTK_Everywhere/AP-Config/index.html
Firmware/RTK_Everywhere/AP-Config/src/main.js
Firmware/RTK_Everywhere/GNSS_LG290P.h
Firmware/RTK_Everywhere/GNSS_LG290P.ino
Firmware/RTK_Everywhere/GNSS_UM980.h
Firmware/RTK_Everywhere/GNSS_UM980.ino
Firmware/RTK_Everywhere/menuMessages.ino

This adds a serial and Web Config option to 'Set Defaults to PPP Logging' to the Torch and Postcard platforms. By default, the following sentences are enabled on the LG290P and UM980:
* RTCM1019
* RTCM1020
* RTCM1042
* RTCM1046
* RTCM1074
* RTCM1084
* RTCM1094
* RTCM1124
These messages are enabled at 1/30Hz or once every 30 seconds. This is to minimize the size of the logs and because the major services decimate any submission to every 30 seconds anyway.
The default NMEA messages are enabled at 1Hz so that if a user connects over Bluetooth (likely with the Torch), the device will act normal (if a little slower than the default 2Hz). This is to reduce log size, but also allow the user and the display on the Postcard (the SIV indicator requires GSV which is the biggest data offender), to …

Add raw logging to Torch and Postcard

---

Firmware/RTK_Everywhere/Network.ino

With `settings.debugNetworkLayer` enabled, going into WiFi web config mode causes a crash:
`networkInterfaceTable[index].name` goes out of bounds; `index` is equal to `NETWORK_OFFLINE`, not less than it
I'm not sure if my fix is what is actually wanted / needed? But at least it prevents the code from going bang...

Prevent crash in networkUserAdd debug print
